sudo: required
language: bash
services:
- docker
script:
- docker build -t keboola/docker-rstudio .
after_success:
- docker images
deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    tags: true
notifications:
  slack:
    secure: fRVSNiGtTdKQsP+LOVeYlK/Ed2NjB4HoZgBFkBqkirNlS8ZuvyQSto6xr1VNHxRCBx6DjeyXwyHD1OPAX6/CkcTcOaNYFXJnSTmrEjRtA8lK021t6xyCiUtuP3LLC67ukUl59zx2eVMbp3H2AVRUoJQ/rCwxGjFx4HJqQdiQPH65Fj6YGeG/YCyXywYU1GwaEOW0IcioMY+Ltsn34blgfHZ5ZYlEHj79HJu66T/muYi5P+YPwzkn3+/AeRDR0JHb6kAs2EOOtbu55KVtbdpsMEgBFqtMOm74rDQW2gGQ0sw841A/sQ4Yolmi86OKKlQILrIO0rmkMMqNKeotHEeOiT2pQOwwzc82pylj6CQGJKLBU/Id7qI6MUsSGLZZD4iNaxh1kKOCFhdPSPRiSlFXcFDS9wNhY7/ZUKDU2hOAZJDTgSCcgrqPGfN/JwTbIO5UkLw5bMDbCXP9Bw+56JGhiHwMUMc+3cHwQAgR5ueAzajMoQUKpnwAxlyemaCF6d8WU2b0unxFecaYi7n3G8a12biD+imvglBCaE1I0E8goPjmEZJmizNtB8barDIQMMJS1aU95GvO9XfwxG7bJXuk18L0XJkJ7GdIWeItehh4UcWlS0tZbloxbfXXbPlJa/43nnV1ZyA3ud0w7Dzy0GuE8xHacLcKNHguHL2bIhUMIwU=
    rooms:
      secure: l6dIGVEfVkd0URQObQytUDlq0G346Oy8hjDBNl/44W/lUjBg/XW+87JFm9gRojwQ33yrwq5B8/qHBKrLJpkzbSvR2Q+TXLoYDEn+Wu/52qnlJ49ZGG42Gs/viIVMecck9S4rpU2j0+LOp1RgD4ecIVbKTcPy1ZChoNqlKuS1Tjii5aKFn0jmVqtHNTBkPHh+KgGlUS7BzbIE8Qjjo+6UjmCnjsn2Qi9f0Akxm9MnHX12LsuEJURSgTCmspO0bFSSYIHTeAUg/c6XWatPOx020mP/zE8TfoaYmABeKD7CIGZLjV2kPUbPkgCCT7/tuL/P9P2aZVbupAlDVQV5i+Faq6mGIprnS7wkV21Pp0bjZ30JGDqx0w+y7zw3T4VFfZSKEO+8HzGbkkQgaMOCrdQTwiUw5l5CzR+4eSEoBC25AAbfbXyWCWMm5ux70fZfftzw+hRoOg6tPOV6tGViA6NrgHFt76xWExzCD8wEbhjZRrGHmEZfaf7umr5zOF3UP8rOzj07sXbQvOllo+VsaEgNyL9XwcxQ+QJ49doJ5Uv43RFuOM1m+Hfc93S86c63LWZPkA2cd9vxWJRmNb/4964xbNf/Y1dtbwIsa9xCmJTr+uisqVI5nADLeRJ/GKeyimi3XpK1xNqwcrS/+nxewZN7WqVLvtTG1Lo3ALJ0zvx9+Lk=
  email: false
