version: "2"
services:
  data-loader:
    image: php:7-apache
  rstudio:
    build: .
    links:
      - data-loader
    environment:
      USER: martin
      PASSWORD: test
  proxy:
    image: nginx:1.13
    links:
      - rstudio
    ports:
      - "6200:80"
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf
